
theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes 
    - navigation.top
    - content.code.copy

  palette:
    # Light mode / dark mode
    # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
    # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/Poster_Plot_trans.png
    
  icon:
    repo: fontawesome/brands/github  # GitHub logo in top right
    # logo: Images/Poster_Plot.png #material/telescope
    # favicon: "Images/Poster_Plot.png" #material/telescope

site_name: xenomorph
docs_dir: docs/
site_description: Tutorials for xenomorph.
site_author: Ryan white
site_url: https://ryanwhite1.github.io/xenomorph/
repo_url: https://github.com/ryanwhite1/xenomorph
repo_name: ryanwhite1/xenomorph
edit_uri: "" 

# strict: true # Prevent builds with warnings

plugins:
  - mkdocs-jupyter:
  - search
  - autorefs
  # - exclude:
  #     glob:
  #       - Images/*
  # - simple:
  #     ignore:
  #       - tests
  #       - src
  #       - build
  #       - Images
  #       - deprecated
  #       - HMC_Testing
  
  - mkdocstrings:
        handlers:
          python:
            options:
              docstring_style: "numpy"

markdown_extensions:
  # - mdx_math  #https://stackoverflow.com/questions/27882261/mkdocs-and-mathjax <- source!
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.tasklist:
        custom_checkbox: true
  - toc:
      toc_depth: 2
  
  

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# ===== Navigation =====
nav:
    - Home: index.md

    - Tutorials:
      - Plotting a Spiral:         tutorials/First_Spiral.ipynb
      - The xenomorph GUI:         tutorials/gui.ipynb
      - Velocity Slicing a Nebula: tutorials/velocity_cube.ipynb
    
    - Reference:
      - Geometry: Reference/geometry.md
      - GUI: Reference/gui.md
      - Systems: Reference/systems.md
            

    # - FAQ & Troubleshooting: faq.md
    # - Change Log: CHANGELOG.md
    # - Contributing: CONTRIBUTING.md